@startuml
'https://plantuml.com/state-diagram

title Container Service 4.0


state "XNAT Container Service" as xcs {
    state "Command Resolution" as res {
      [*] --> Idle
      Idle --> Configuring : EvConfig
      Configuring --> Idle : EvConfig
    }

    res --> lqs : Launch Request

    state "Launch Queue Service" as lqs {
    }
}

state "Remote Execution Enviroment" as ree {

  state "XNAT Job Doer" as xjd {
     state "Jobs\nRequester" as jr {
        State1 -> State2
     }

     state "Job Status\nUpdater" as jsu {
     }

     state "Resource\nBroadcaster" as rb {
     }
  }
}
rb --> lqs : Broadcast
jr --> lqs : Request
jsu --> lqs : Update

@enduml