@startuml
'https://plantuml.com/


frame "XNAT" as xnat {
frame "CS4"
}

cloud "Container Registry" as hub {
}

node SLURM {
}

node SWARM {
}

node Kubernetes {
}

actor "Container User" as user

frame "SLURM Agent" as slm_agnt
frame "Docker Agent" as dkr_agnt
frame "Kubernetes Agent" as k8s_agnt


[CS4] <-down- slm_agnt
[CS4] <-down- dkr_agnt
[CS4] <-down- k8s_agnt

top to bottom direction
[user] <--> [CS4]
slm_agnt <-> SLURM
dkr_agnt <-> SWARM
k8s_agnt <-> Kubernetes

left to right direction

CS4 --> hub
SLURM --> hub
SWARM --> hub
Kubernetes --> hub

@enduml