

@startjson
{
    "id" : "int",
    "label" : "string",
    "description" : "string",
    "command" : {
    },
    "agent" : {
    },
    "directory_mapping" :
        {"/dir/in/container" : "/dir/on/xnat"}


}
@endjson


